USE bradymt29;

DROP TABLE IF EXISTS notebook;
CREATE TABLE notebook (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  posted TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  message TEXT NULL
);

INSERT INTO notebook VALUES(NULL, NULL, "Hello World");
INSERT INTO notebook VALUES(NULL, NULL, "Test post by Matt");

